### ISSUE TITLE
Failed to run nav_to_pose example - amcl/get_state service not available

### ISSUE THREAD

**Issue by BertVanAcker** [turtlebot/turtlebot4_tutorials#2]
**Please provide the following information:**
 - OS:  Ubuntu 20.04
 - ROS Distro:  Galactic
 - Built from source or installed: Debian install
 

 **Expected behaviour**
 I'm trying to run the nav_to_pose python example with the nav2 simple commander. Normally, this would command the robot to dock, undock, set initial position and move to the desired position. 

 **Actual behaviour**
I cannot run the python nav_to_pose example, I continously get the following message:

_[basic_navigator]: amcl/get_state service not available, waiting..._

I also tried launching the turtlebot_navigation package before running the nav_to_pose example but this also did not work, this produces the following message:

_Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist_

**To Reproduce**
Provide the steps to reproduce:
1. launch turtlebot4 without slam (ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off) -> does this work without the lidar?
2. launch nav_to_pose example

**Comment by roni-kreinin** [comment]
The RPLIDAR is still required for localization as the sensor data is used for figuring out where the robot is on the map.

Also can you try updating your `turtlebot4_navigation` package to make sure it is on version 0.1.1?
