### ISSUE TITLE
malfunction feedback in turtlebot4-python-tutorials examples bug

### ISSUE THREAD

**Issue by alain-lnpcrd** [turtlebot/turtlebot4_tutorials#8]
### Robot Model

Turtlebot4 Lite

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

a11a77da2dc5039d75d2581b481b184c041eb52a

### Expected behaviour

The feedback follows each stage of the destinations until their end, giving the remaining time to go for each.

### Actual behaviour

Lots of malfunctions with examples of turtlebot4-python-tutorials mainly related to feedback. Others seem to relate to the use of packages with "apt lis"t or with " sources compiled with 'colcon build' ", but I am not very sure being a beginner with ROS2 and its range of tools all more complicated than the others.
So finally I eliminated all "colcon build --symlink-install" builds other than package turtlebot4-tutorials.

conclusion : applications using "feedback" malfunction.
The feedback starts but stop with goal failed and often the robot has not moved.
Having removed the "dock" instructions at the end of the examples, the robot will sometimes go as far as the destination for "nav_to_pose" or not.
For "nav_through_poses", it's much more complicated and eventually it will launch after a "goal failed!" and fail at the first destination.
For "follow_waypoints", it goes after the end point of the last goal.

It's too late now for me to try the other examples.

### Error messages

```bash
goal failed! 
and others
```

### To Reproduce

repeat the examples under the same conditions

### Other notes

with all the malfunctions we wonder if ros2 is a reliable system for doing robotics.

I would not recommend it to Ukarinians to operate their drones of any kind.

**Comment by alain-lnpcrd** [comment]
Everythings come from :
[bt_navigator-5] [WARN] [1709285212.221378639] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!

**Comment by hilary-luo** [comment]
@alain-lnpcrd 

Can you please modify your issue in the following ways:

1. Please indicate the package version properly (if you are running this from source then please provide the commit hash). 
2. Please update the Error Messages section to contain the full terminal output of the commands that are failing (including the initial command itself)
3. Please elaborate on the "To Reproduce" section. The point of this section is for you to provide the exact details I need to be able to reproduce the issue that you are seeing. If you are running through a particular example then you can link the particular example but even better than that, please share the exact commands that you are running. The more vague the directions, the less likely I will be able to reproduce what you are seeing. Also explicitly state any such "conditions" that you mention.
 
Once I have this information then I will see if I can reproduce your system. 

That being said, is there any reason that you are building this from source and not using installed debians? If you are a beginner running things from source then you will need to be prepared to learn ROS and work through the errors that may come with that. ROS is an incredibly powerful tool for robotics but that also means that it is incredibly complex. Any beginner who starts using ROS developer tools will go through having to troubleshoot systems and learning how to set them up properly. This experience won't tell you how reliable of a system ROS is or what you can do with it. That being said, I don't think your issues are necessarily ROS specific either, these are they types of challenges you may run into when you run any open source project from source on your own machine.
